### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by therealOri** [Narasimha1997/fake-sms#1]
Function times out after requesting to add a number while using `./fake-sms`

# Error Message.
```
2021/03/02 16:14:17 Get "https://upmasked.com/api/sms/numbers": dial tcp 116.203.74.252:443: i/o timeout
```

# Error message ran via go run.
```
2021/03/02 16:15:12 Get "https://upmasked.com/api/sms/numbers": dial tcp 116.203.74.252:443: i/o timeout
exit status 1
```
Function timeout when using `go run main.go`

**Comment by Narasimha1997** [comment]
Hi @therealOri , thanks for reaching out.

Yes, I am able to reproduce the issue. https://upmasked.com is down as of now. We will wait for it to be available.

**Comment by therealOri** [comment]
> Hi @therealOri , thanks for reaching out.
> 
> Yes, I am able to reproduce the issue. https://upmasked.com is down as of now. We will wait for it to be available.

Ok, Thanks for getting back to me and letting me know the issue!
If you can, let me know when it's back up/online and that would be great.






# Update 3/3/2021

```2021/03/03 12:03:03 Get "https://upmasked.com/api/sms/numbers": dial tcp 116.203.74.252:443: connect: connection refused```
This is the error I get now. It doesn't timeout, it just refuses connections.
@Narasimha1997

**Comment by therealOri** [comment]
# Update 3/6/2021

Using `./fake-sms` and `go run main.go` both throw the following error now.

```
2021/03/06 10:55:42 Get "https://upmasked.com/api/sms/numbers": x509: certificate is valid for s.rominimal.club, not upmasked.com
```

Not sure what causes this but would like to know.

**Comment by Narasimha1997** [comment]
@therealOri 
Hey, happy weekend. 

I managed to add a new service provider since upmasked removed their service recently. Please checkout now. The new service provider provides you more numbers across more countries. Make sure you have the latest main branch snapshot.

**Comment by therealOri** [comment]
> @therealOri 
> Hey, happy weekend. 
> 
> I managed to add a new service provider since upmasked removed their service recently. Please checkout now. The new service provider provides you more numbers across more countries. Make sure you have the latest main branch snapshot.


@Narasimha1997 
Alrighty!
Thanks for the update and the work in this repo!

Have a happy rest of the weekend.
