### ISSUE TITLE
No new number available

### ISSUE THREAD

**Issue by Kylvan-8** [Narasimha1997/fake-sms#10]
![image](https://user-images.githubusercontent.com/61290148/152822417-02986f92-1efc-4b52-9f23-efd3d4492e01.png)

Hello,
Is it normal ?

Regards

**Comment by Narasimha1997** [comment]
Let me check

**Comment by enema-combatant** [comment]
Also have this issue...

**Comment by swordapi** [comment]
Same

**Comment by Narasimha1997** [comment]
Had been busy. Will check out soon

**Comment by swordapi** [comment]
Ty

**Comment by BigGod12** [comment]
i could not run the tool..following the README.md 
I could only execute these commands = 
export GOBIN=$PWD/bin
go install

got these error message = 
[root@ip-172-26-8-22 go]# go install
package .: no Go files in /root/go

Anything i`m getting wrong on this please
thanks for the reply

**Comment by voidsipp** [comment]
> i could not run the tool..following the README.md I could only execute these commands = export GOBIN=$PWD/bin go install
> 
> got these error message = [root@ip-172-26-8-22 go]# go install package .: no Go files in /root/go
> 
> Anything i`m getting wrong on this please thanks for the reply

Make sure you CD into the directory you downloaded the tool

**Comment by voidsipp** [comment]
> ![image](https://user-images.githubusercontent.com/61290148/152822417-02986f92-1efc-4b52-9f23-efd3d4492e01.png)
> 
> Hello, Is it normal ?
> 
> Regards

Getting the same thing on my copy too.

**Comment by r4lix** [comment]
yep, no new number available

**Comment by Narasimha1997** [comment]
This issue is fixed in the latest commit.
