### ISSUE TITLE
No new numbers available right now

### ISSUE THREAD

**Issue by Ipnotisen** [Narasimha1997/fake-sms#16]
![image](https://github.com/Narasimha1997/fake-sms/assets/72452447/95baba51-9e72-444d-9914-5af89c9035f5)
As the title says, using the last update. How can i fix that ?

**Comment by ErbaZZ** [comment]
The format of the source website has changed, so the scraper made for the old format does not work.

Please see #17 for the fix.

**Comment by Ipnotisen** [comment]
Thanks for that !
