### ISSUE TITLE
Certificate Error

### ISSUE THREAD

**Issue by BitThr3at** [Narasimha1997/fake-sms#2]
Got a certificate Error like the below:
![image](https://user-images.githubusercontent.com/45028933/110218560-62c84c00-7ee0-11eb-97fe-82ecf31652ac.png)

And I tried to fix it by adding an insecure global  flag in the HTTP client
![image](https://user-images.githubusercontent.com/45028933/110218611-ae7af580-7ee0-11eb-98a8-3fffef6a5143.png)

but then I got a different error
![image](https://user-images.githubusercontent.com/45028933/110218635-d5392c00-7ee0-11eb-88ea-cedaf9e77cef.png)

**Comment by BitThr3at** [comment]
I think the service isn't working anymore
![image](https://user-images.githubusercontent.com/45028933/110218915-4e854e80-7ee2-11eb-8d45-6db3559c6601.png)

**Comment by devmadhavvv** [comment]
Yeahh same problem

**Comment by Narasimha1997** [comment]
@BitThr3at @carbseater 
Yes. The service went down few days back. 
Since today is a weekend, I will change the service provider. The tool's interface will remain same.

**Comment by Narasimha1997** [comment]
@BitThr3at @carbseater 

I managed to add a new provider, it supports more free numbers than upmasked. Can you check out and tell me? If everything works fine??

PS : Make sure you have the latest main branch

**Comment by devmadhavvv** [comment]
@Narasimha1997 sure, thanks

**Comment by Narasimha1997** [comment]
Closing this, as we have changed the service provider.
