### ISSUE TITLE
Upmasked GET request failing

### ISSUE THREAD

**Issue by Franklin-oss** [Narasimha1997/fake-sms#3]
`
2021/03/26 08:13:41 Failed to make GET request https://upmasked.com/api/sms/messages/447418310977
`
Get my messages for any number or Add a new number does not work. Connection is refused
`2021/03/26 08:16:35 Get https://upmasked.com/api/sms/numbers: dial tcp 116.203.74.252:443: connect: connection refused`

**Comment by Narasimha1997** [comment]
@Franklin-oss 
Can you make sure you're using the latest master branch?
