### ISSUE TITLE
No instructions for installation

### ISSUE THREAD

**Issue by sm0lbr4in** [Narasimha1997/fake-sms#4]
I don’t know if I just lack the understanding, but once I clone the files and unzip the file onto my desktop, how do I actually run the code? I assume it has something to do with the terminal but then again I’m probably just dumb.

**Comment by Ashish07143** [comment]
Same question 
Can I run this on phone ?
In termux ?

**Comment by Narasimha1997** [comment]
1. Install Golang. Check here [check here](https://golang.org/doc/install)
2. Then clone the project.
3. Build the project.  Just do 
     ```
      export GOBIN=$PWD/bin
      go install
     ```
4. You should see the binary installed in `project-directory/bin` by name `fake-sms`.
5. Then run like this:
    ```
       cd bin
       ./fake-sms
    ```
It should run normally.

**Comment by Narasimha1997** [comment]
Closing this. Let me know if you have any issues.
