### ISSUE TITLE
Invalid phone number

### ISSUE THREAD

**Issue by sm0lbr4in** [Narasimha1997/fake-sms#5]
I’m using this code for discord, and every single number listed pops up the message “invalid phone number”. I think your code is messed up lol.

**Comment by Narasimha1997** [comment]
Hi, it is not messed up LoL. I am not able to reproduce the issue. Let me know if you have issues, or give me the detailed explanation.

**Comment by Kylvan-8** [comment]
So many of the phones numbers aren't valid for google voice and even if valid on Discord it's impossible to get the message, it's always empty even if you try to resend the code.

Is it still working ?

Thanks for the program.

**Comment by Narasimha1997** [comment]
This is just a client tool. It has nothing to do with the numbers being invalid. Maybe Google has some verification mechanism that does not allow fake numbers like this. But these numbers work for almost most of the normal websites.

**Comment by Kylvan-8** [comment]
> This is just a client tool. It has nothing to do with the numbers being invalid. Maybe Google has some verification mechanism that does not allow fake numbers like this. But these numbers work for almost most of the normal websites.

Maybe but when i choose to read messages it's always empty, at least on all the numbers i've checked.

**Comment by Narasimha1997** [comment]
Hi, yes you are right. There was an issue. The service provider had changed some table indexes, which caused the issue.

Fixed it in the latest commit. Pull the latest source code and start using it.
Thanks
