### ISSUE TITLE
Exec format error x86_64 plateform

### ISSUE THREAD

**Issue by Kylvan-8** [Narasimha1997/fake-sms#9]
Hello,
This is the version i'm using on windows 10 (64 bit processor) with git bash : go version go1.17.6 windows/amd64.

This is what i get when trying to launch the program 

$ ./fake-sms
bash: ./fake-sms: cannot execute binary file: Exec format error

What i'm doing wrong ?

P.S. : thanks for the program !

**Comment by Narasimha1997** [comment]
Hi, this is the linux binary. But you can build on windows. 

Just clone the repository and run 
```
go install
```
